---
platform: linux
image_resource:
  type: docker-image
  source:
#    repository: gliderlabs/alpine
    repository: concourse/concourse-ci

inputs:
- name: tools
- name: upstream
- name: target

outputs:
- name: target-sync

run:
  path: tools/scripts/sync-fork.sh
